# Generated by Django 3.0.8 on 2020-08-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_fee', models.FloatField(verbose_name='广告费')),
                ('amazon_id', models.PositiveIntegerField(verbose_name='亚马逊店铺ID')),
                ('amazon_name', models.CharField(max_length=50, verbose_name='亚马逊店铺渠道')),
                ('ams_ads_fee', models.FloatField(max_length=50, verbose_name='AMS广告费')),
                ('asin', models.CharField(max_length=50, verbose_name='ASIN')),
                ('asin_url', models.URLField(max_length=255, verbose_name='亚马逊产品链接')),
                ('category', models.CharField(max_length=50, verbose_name='品类')),
                ('compensate', models.FloatField(verbose_name='物料赔偿')),
                ('dev_team_id', models.PositiveIntegerField(verbose_name='开发团队ID')),
                ('dev_team_name', models.PositiveIntegerField(verbose_name='开发团队')),
                ('develop_user', models.PositiveIntegerField(verbose_name='开发人员ID')),
                ('develop_username', models.CharField(max_length=255, verbose_name='开发人员')),
                ('ed_sku', models.CharField(max_length=100, verbose_name='E登SKU')),
                ('evaluation_refund', models.FloatField(verbose_name='测评费用')),
                ('fba_qty', models.PositiveIntegerField(verbose_name='FBA库存')),
                ('fba_reserved_qty', models.PositiveIntegerField(verbose_name='FBA预留库存')),
                ('fba_sell_qty', models.PositiveIntegerField(verbose_name='FBA可销售库存')),
                ('fba_unsell_qty', models.PositiveIntegerField(verbose_name='FBA不可销售库存')),
                ('fee', models.CharField(max_length=50, verbose_name='广告费')),
                ('first_leg', models.FloatField(verbose_name='头程')),
                ('fixed_cost', models.FloatField(verbose_name='固定成本')),
                ('freight', models.FloatField(verbose_name='运费')),
                ('gross_profit', models.FloatField(verbose_name='毛利')),
                ('inventory', models.CharField(max_length=255, verbose_name='库存')),
                ('level', models.PositiveSmallIntegerField(verbose_name='产品等级ID')),
                ('level_txt', models.CharField(max_length=50, verbose_name='产品等级')),
                ('lightning_deals', models.PositiveIntegerField(verbose_name='秒杀活动订单')),
                ('order_qty', models.PositiveIntegerField(verbose_name='订单产品数量')),
                ('orders', models.PositiveIntegerField(verbose_name='订单数量')),
                ('price', models.FloatField(verbose_name='订单金额')),
                ('product_name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('purchase_cost', models.FloatField(verbose_name='采购成本')),
                ('refund', models.FloatField(verbose_name='退款金额')),
                ('refund_qty', models.PositiveIntegerField(verbose_name='退款数量')),
                ('sell_sku', models.CharField(max_length=255, verbose_name='渠道销售SKU')),
                ('storage_charges', models.FloatField(verbose_name='仓储费')),
                ('tax_fee', models.FloatField(verbose_name='税费')),
                ('team_id', models.PositiveIntegerField(verbose_name='销售小组ID')),
                ('team_name', models.CharField(max_length=255, verbose_name='销售小组')),
                ('team_user', models.PositiveIntegerField(verbose_name='销售ID')),
                ('team_username', models.CharField(max_length=255, verbose_name='销售')),
                ('total_qty', models.PositiveIntegerField(verbose_name='总数量')),
                ('transport_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='转运费')),
                ('turn_days', models.CharField(max_length=50, verbose_name='周转天数')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='分组名称')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='品牌名称')),
                ('manager', models.CharField(default='', max_length=255, verbose_name='小组组长')),
                ('members', models.CharField(default='', max_length=255, verbose_name='小组成员')),
            ],
        ),
    ]
