# Generated by Django 3.0.8 on 2020-08-21 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsaledetail',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
