# Generated by Django 3.0.8 on 2020-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_auto_20200821_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaledetail',
            name='asin_url',
            field=models.CharField(max_length=255, verbose_name='亚马逊产品链接'),
        ),
    ]
