# Generated by Django 3.0.8 on 2020-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0004_auto_20200821_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaledetail',
            name='dev_team_name',
            field=models.CharField(max_length=255, verbose_name='开发团队'),
        ),
    ]
