# Generated by Django 3.0.8 on 2020-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0005_auto_20200821_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaledetail',
            name='lightning_deals',
            field=models.FloatField(verbose_name='秒杀活动订单'),
        ),
    ]
