# Generated by Django 3.0.8 on 2020-08-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0006_auto_20200821_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesteam',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='分组所属品牌'),
        ),
        migrations.AlterField(
            model_name='salesteam',
            name='members',
            field=models.CharField(default='', max_length=800, verbose_name='小组成员'),
        ),
    ]
