# Generated by Django 3.0.8 on 2020-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0007_auto_20200822_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80, verbose_name='销售名')),
            ],
        ),
        migrations.CreateModel(
            name='SaleTeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveIntegerField(verbose_name='销售团队ID')),
                ('sales_id', models.PositiveIntegerField(verbose_name='销售用户ID')),
                ('manager', models.PositiveSmallIntegerField(default=0, verbose_name='是否组长')),
            ],
        ),
    ]
