# Generated by Django 3.0.8 on 2020-07-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(default='', max_length=50, verbose_name='单据类型')),
                ('title', models.CharField(default='', max_length=100, verbose_name='单据名称')),
                ('order_num', models.CharField(default='', max_length=50, verbose_name='订单号')),
                ('tracking_num', models.CharField(default='', max_length=50, verbose_name='物流跟踪号')),
                ('location', models.CharField(default='', max_length=255, verbose_name='文件保存位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
