# Generated by Django 3.0.8 on 2020-07-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hash',
            field=models.CharField(db_index=True, default='', max_length=32, verbose_name='文件hash值'),
        ),
    ]
