# Generated by Django 3.0.8 on 2020-07-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_invoice_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='hash',
        ),
    ]
